### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by caliendojulien** [romualdrlc/ProjetSortirGroupe2#1]
Utiliser des constantes dans une entité permet de rendre le code plus clair.
Par exemple, dans l'entité **Etat** les constantes suivantes :
```
const ETAT_EN_CREATION = 'En création';
const ETAT_OUVERT = 'Ouvert';
const ETAT_FERME = 'Fermé';
const ETAT_ANNULE = 'Annulé';
const ETAT_EN_COURS = 'En cours';
```
Permettraient d'utiliser des `Etat::ETAT_OUVERT` un peu partout dans le code des contrôleurs.
Comme par exemple :
`findOneBy(['etat' => Etat::ETAT_OUVERT])`

**Comment by romualdrlc** [comment]
Ça marche on modifiera demain
Merci

Le mar. 30 août 2022 à 23:05, Caliendo Julien ***@***.***> a
écrit :
